-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP database IF exists DBEXERCICIOCOMPOSTO2;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIOCOMPOSTO2;

-- CONECTANDO NO BANCO DE DADOS 
USE DBEXERCICIOCOMPOSTO2;
-- CRIANDO TABELAS
CREATE TABLE FUNCIONARIO (
IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (150) NOT NULL,
TELEFONE_CELULAR INT,
TELEFONE_RESIDENCIAL INT,
TELEFONE_RECADO INT,
PRIMARY KEY (IDFUNCIONARIO)
);