-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO16;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO16;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO16;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE MUSICA (
	IDMUSICA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , CANTOR VARCHAR(120) NOT NULL
    , GENERO VARCHAR(50)
    , PRIMARY KEY (IDMUSICA)
);

CREATE TABLE MUSICA (
	IDUSUARIO INT NOT NULL 
	, IDMUSICA INT NOT NULL 
    , PRIMARY KEY (IDUSUARIO, IDMUSICA)
    , FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
	, FOREIGN KEY (IDMUSICA) REFERENCES MUSICA (IDMUSICA)
);