DROP DATABASE IF EXISTS DBEXERCICIO20;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO20;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO20;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , DT_PEDIDO DATE NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE CATEGORIA (
	IDCATEGORIA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDCATEGORIA)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRECO DECIMAL(8,2) NOT NULL
    , IDCATEGORIA INT NOT NULL
    , PRIMARY KEY (IDPRODUTO)
    , FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA (IDCATEGORIA)
);

CREATE TABLE ITEM_PEDIDO (
	IDEMPRESTIMO INT NOT NULL AUTO_INCREMENT
	, IDPEDIDO INT NOT NULL 
	, IDPRODUTO INT NOT NULL 
    , QUANTIDADE INT NOT NULL
    , PRECO_UNITARIO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDPEDIDO, IDPRODUTO)
    , FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (IDPEDIDO)
	, FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
);