DROP DATABASE IF EXISTS DBEXERCICIO19;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO19;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO19;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TURMA VARCHAR(500) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(120) NOT NULL
    , AUTOR VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDLIVRO)
);

CREATE TABLE EMPRESTIMO (
	IDEMPRESTIMO INT NOT NULL AUTO_INCREMENT
    , DT_EMPRESTIMO DATE NOT NULL
    , DT_DEVOLUCAO DATE 
	, IDALUNO INT NOT NULL 
	, IDLIVRO INT NOT NULL 
    , PRIMARY KEY (IDEMPRESTIMO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
	, FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
);