-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO25;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO25;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO25;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE INSTRUTOR (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE PROFESSOR (
	IDPROFESSOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL 
    , IDINSTRUTOR INT NOT NULL
    , PROFESSOR INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , DT_FINAL DATE NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
	DT_MATRICULA DATE NOT NULL
);

CREATE TABLE MATERIAL (
	IDMATERIAL INT NOT NULL 
    , NOME VARCHAR(120) NOT NULL
    , LINK_MATERIAL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDMATERIAL)
);

CREATE TABLE ASSISTIR (
	IDASSISTIR INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDASSISTIR)
);


CREATE TABLE COMENTARIO (
	IDCOMENTARIO INT NOT NULL 
    , IDAULA INT NOT NULL
    , DT_CONENTARIO DATE NOT NULL
    , IDALUNO INT NOT NULL
    , TEXTO_COMENTARIO VARCHAR(200) NOT NULL
    , IDPROFESSOR INT
    , IDINSTRUTOR INT
    , TEXTO_RESPOSTA VARCHAR(200)
    , PRIMARY KEY (IDCOMENTARIO)
);

-- CORRIGINDO TABELA DE ALUNO 
ALTER TABLE ALUNO 
ADD IDALUNO INT NOT NULL,
ADD PRIMARY KEY (IDALUNO)
;
-- CORRIGINDO TABELA DE INSTRUTOR 
ALTER TABLE INSTRUTOR 
ADD IDINSTRUTOR INT NOT NULL,
ADD PRIMARY KEY (IDINSTRUTOR)
;
-- CORRIGINDO TABELA DE CURSO 
ALTER TABLE CURSO 
DROP COLUMN PROFESSOR ;

-- CORRIGINDO TABELA DE MATRICULA 
ALTER TABLE MATRICULA
ADD IDMATRICULA INT NOT NULL,
ADD IDALUNO INT NOT NULL,
ADD IDCURSO INT NOT NULL,
ADD PRIMARY KEY (IDMATRICULA),
ADD FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO),
ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO);

CREATE TABLE AULA (
IDAULA INT NOT NULL,
DT_AULA INT NOT NULL,
IDCURSO INT NOT NULL,
PRIMARY KEY (IDAULA),
FOREIGN KEY (IDCURSO)REFERENCES CURSO (IDCURSO)
);
-- CORRIGINDO TABELA DE MATERIAL 
ALTER TABLE MATERIAL
ADD IDAULA INT NOT NULL,
ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA);

-- CORRIGINDO TABELA DE ASSISTIR 
ALTER TABLE ASSISTIR
ADD IDAULA INT NOT NULL,
ADD DT_ACESSO DATE,
ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO),
ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA);

-- CORRIGINDO TABELA DE COMENTARIO 
ALTER TABLE COMENTARIO
DROP COLUMN IDPROFESSOR,
ADD FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO),
ADD FOREIGN KEY (IDAULA) REFERENCES AULA (IDAULA),
ADD FOREIGN KEY (IDINSTRUTOR) REFERENCES INSTRUTOR (IDINSTRUTOR);


DROP TABLE PROFESSOR

