-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO25;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO25;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO25;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE INSTRUTOR (
	NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE PROFESSOR (
	IDPROFESSOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT
    , IDINSTRUTOR INT NOT NULL
    , PROFESSOR INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , DT_FINAL DATE NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
	DT_MATRICULA DATE NOT NULL
);

CREATE TABLE MATERIAL (
	IDMATERIAL INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , LINK_MATERIAL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDMATERIAL)
);

CREATE TABLE ASSISTIR (
	IDASSISTIR INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDASSISTIR)
);


CREATE TABLE COMENTARIO (
	IDCOMENTARIO INT NOT NULL AUTO_INCREMENT
    , IDAULA INT NOT NULL
    , DT_CONENTARIO DATE NOT NULL
    , IDALUNO INT NOT NULL
    , TEXTO_COMENTARIO VARCHAR(200) NOT NULL
    , IDPROFESSOR INT
    , IDINSTRUTOR INT
    , TEXTO_RESPOSTA VARCHAR(200)
    , PRIMARY KEY (IDCOMENTARIO)
);