-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO15;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO15;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO15;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , DT_NASCIMENTO DATE NOT NULL
    , CIDADE VARCHAR(120)
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT
    , DT_MATRICULA DATE NOT NULL
    , CURSO VARCHAR(120) NOT NULL
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);
