DROP DATABASE IF EXISTS DBEXERCICIO22;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO22;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO22;

CREATE TABLE FILIAL (
	IDFILIAL INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15)
    , PRIMARY KEY (IDFILIAL)
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , IDFILIAL INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15)
    , PRIMARY KEY (IDCLIENTE)
    , FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
);

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT
    , IDFILIAL INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , DTADMISSAO DATE NOT NULL
    , PRIMARY KEY (IDFUNCIONARIO)
    , FOREIGN KEY (IDFILIAL) REFERENCES FILIAL (IDFILIAL)
);

CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , DESCRICAO VARCHAR(120) NOT NULL
    , DTINICIO DATE NOT NULL
    , PRIMARY KEY (IDPROJETO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
    
CREATE TABLE ALOCADO (
	IDFUNCIONARIO INT NOT NULL 
    , IDPROJETO INT NOT NULL
    , PRIMARY KEY (IDFUNCIONARIO, IDPROJETO)
    , FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
    , FOREIGN KEY (IDPROJETO) REFERENCES PROJETO(IDPROJETO)
);
