DROP DATABASE IF EXISTS DBEXERCICIO21;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO21;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO21;

-- CRIANDO AS TABELAS
CREATE TABLE CRIMINOSO (
	IDCRIMINOSO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , DT_NASCIMENTO DATE NOT NULL
    , PRIMARY KEY (IDCRIMINOSO)
);

CREATE TABLE VITIMA (
	IDVITIMA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , DT_NASCIMENTO DATE NOT NULL
    , PRIMARY KEY (IDVITIMA)
);

CREATE TABLE CRIME (
	IDCRIME INT NOT NULL AUTO_INCREMENT
    , DT_CRIME DATE NOT NULL
    , LOCAL_CRIME VARCHAR(200) NOT NULL
    , PRIMARY KEY (IDCRIME)
);

CREATE TABLE ARMA (
	IDARMA INT NOT NULL AUTO_INCREMENT
    , DESCRICAO VARCHAR(120) NOT NULL
    , CATEGORIA VARCHAR(50)
    , NUMERO_INDENTIFICACAO INT
    , PRIMARY KEY (IDARMA)
);

CREATE TABLE COMETE(
	IDCRIMINOSO INT NOT NULL
    , IDCRIME INT NOT NULL
    , PRIMARY KEY (IDCRIMINOSO, IDCRIME)
    , FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO)
    , FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);

CREATE TABLE SOFRE(
	IDVITIMA INT NOT NULL
    , IDCRIME INT NOT NULL
    , PRIMARY KEY (IDVITIMA, IDCRIME)
    , FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA)
    , FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);

CREATE TABLE ATACA(
	 IDCRIMINOSO INT NOT NULL
    , IDVITIMA INT NOT NULL
    , PRIMARY KEY (IDVITIMA, IDCRIMINOSO)
    , FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA)
    , FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO)
);

CREATE TABLE USAR(
	IDARMA INT NOT NULL
    , IDCRIME INT NOT NULL
    , PRIMARY KEY (IDARMA, IDCRIME)
    , FOREIGN KEY (IDARMA) REFERENCES ARMA(IDARMA)
    , FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME)
);

