DROP DATABASE IF EXISTS DBEXERCICIO18;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO18;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO18;

-- CRIANDO AS TABELAS
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , EMAIL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(120) NOT NULL
    , CARGA_HORARIA INT NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT
    , DT_MATTRICULA DATE NOT NULL
	, IDALUNO INT NOT NULL 
	, IDCURSO INT NOT NULL 
    , PRIMARY KEY (IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
	, FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO)
);