DROP DATABASE IF EXISTS DBEXERCICIO25;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO25;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO25;

CREATE TABLE RESTAURANTE (
	IDRESTAURANTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDRESTAURANTE)
);

CREATE TABLE CARDAPIO (
	IDCARDAPIO INT NOT NULL AUTO_INCREMENT
	, IDRESTAURANTE INT NOT NULL 
    , NOME VARCHAR(120) NOT NULL
    , PRECO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDCARDAPIO)
    , FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE (IDRESTAURANTE)
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE ENTREGADOR (
	IDENTREGADOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDENTREGADOR)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDENTEGADOR INT
    , DT_PEDIDO DATE NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDENTEGADOR) REFERENCES ENTEGADOR (IDENTEGADOR)
);

CREATE TABLE ITEM_PEDIDO (
	IDPEDIDO INT NOT NULL
    , IDCARDAPIO INT NOT NULL
    , QTDE INT NOT NULL
    , PRECO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDPEDIDO, IDCARDAPIO)
    , FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (IDPEDIDO)
    , FOREIGN KEY (IDCARDAPIO) REFERENCES CARDAPIO (IDCARDAPIO)
);
