-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP database IF exists DBEXERCICIOCOMPOSTO1;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIOCOMPOSTO1;

-- CONECTANDO NO BANCO DE DADOS 
USE DBEXERCICIOCOMPOSTO1;
-- CRIANDO TABELAS
CREATE TABLE FUNCIONARIO (
IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (150) NOT NULL,
DDD_CELULAR int,
NUMERO_CELULAR int,
NOME_P_RECADO VARCHAR (150) NOT NULL,
DDD_RECADO int,
NUMERO_RECADO int,
DDD_RESIDENCIAL int,
NUMERO_RESIDENCIAL int,
PRIMARY KEY (IDFUNCIONARIO)
);