DROP DATABASE IF EXISTS DBEXERCICIO21;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO23;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO23;

CREATE TABLE CURSO (
	IDCURSO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDCURSO)
);

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
	, IDCURSO INT NOT NULL
    , DTMATRICULA DATE NOT NULL
    , PRIMARY KEY (IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO)
);

CREATE TABLE AULA (
	IDAULA INT NOT NULL AUTO_INCREMENT
    , IDCURSO INT NOT NULL
    , DTAULA DATE NOT NULL
    , PRIMARY KEY (IDAULA)
    , FOREIGN KEY (IDCURSO) REFERENCES CURSO(IDCURSO)
);

CREATE TABLE FREQUENCIA (
    IDALUNO INT NOT NULL
	, IDAULA INT NOT NULL
    , PRIMARY KEY (IDALUNO, IDAULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDAULA) REFERENCES AULA(IDAULA)
);

CREATE TABLE RECITAL (
	IDRECITAL INT NOT NULL AUTO_INCREMENT
    , DTRECITAL DATE NOT NULL
    , LOCAL_RECITAL VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDRECITAL)
);

CREATE TABLE PARTICIPA (
    IDALUNO INT NOT NULL
	, IDRECITAL INT NOT NULL
    , PRIMARY KEY (IDALUNO, IDRECITAL)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDRECITAL) REFERENCES RECITAL(IDRECITAL)
);

