-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO17;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO17;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO17;

-- CRIANDO AS TABELAS
CREATE TABLE PROFESSOR (
	IDPROFESSOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , DISCIPLINA VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE TURMA (
	IDTURMA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , ANO INT NOT NULL
    , IDPROFESSOR INT NOT NULL
    , PRIMARY KEY (IDTURMA)
    , FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR)
);