DROP DATABASE IF EXISTS DBEXERCICIO28;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO28;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO28;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL 
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL 
    , PRIMARY KEY (IDVENDA)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL 
    , IDVENDA INT 
    , TITULO VARCHAR(120) NOT NULL
    , AUTOR VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDLIVRO)
    , FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);

CREATE TABLE ALUGUEL (
	IDALUGUEL INT NOT NULL 
    , IDCLIENTE INT NOT NULL
    , IDLIVRO INT NOT NULL
    , DTRESERVA DATE
    , PRIMARY KEY (IDALUGUEL)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
    );
    
	-- CORRIGINDO A TABELA DE VENDA
    ALTER TABLE VENDA 
    ADD COLUMN IDCLIENTE INT NOT NULL,
    ADD COLUMN DTVENDA DATE NOT NULL,
    ADD FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    ;
    
    -- CORRIGINDO A TABELA ALUGUEL (MUDANDO PARA RESERVA)
    RENAME TABLE ALUGUEL TO RESERVA;
    ALTER TABLE RESERVA
    CHANGE COLUMN IDALUGUEL IDRESERVA INT NOT NULL
    ;
  