DROP DATABASE IF EXISTS DBEXERCICIO24;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO24;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO24;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , PRIMARY KEY (IDVENDA)
);

CREATE TABLE LIVRO (
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , IDVENDA INT 
    , TITULO VARCHAR(120) NOT NULL
    , AUTOR VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDLIVRO)
    , FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);

CREATE TABLE ALUGUEL (
	IDALUGUEL INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDLIVRO INT NOT NULL
    , DTRESERVA DATE
    , PRIMARY KEY (IDALUGUEL)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDLIVRO) REFERENCES LIVRO (IDLIVRO)
);