DROP DATABASE IF EXISTS DBEXERCICIO25;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO25;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO25;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , TELEFONE VARCHAR(15) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PROJETO (
	IDPROJETO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , NOME VARCHAR(120) NOT NULL
    , PRAZO DATE NOT NULL
    , ORCAMENTO DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDPROJETO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE DESENVOLVEDOR (
	IDDESENVOLVEDOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , VALOR_HORA DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDDESENVOLVEDOR)
);

CREATE TABLE ALOCADO (
	IDDESENVOLVEDOR INT NOT NULL
    , IDPROJETO INT NOT NULL
    , QTDE_HORAS INT NOT NULL
    , VALOR DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDDESENVOLVEDOR, IDPROJETO)
    , FOREIGN KEY (IDDESENVOLVEDOR) REFERENCES DESENVOLVEDOR(IDDESENVOLVEDOR)
    , FOREIGN KEY (IDPROJETO) REFERENCES PROJETO(IDPROJETO)
);

CREATE TABLE MATERIAL (
	IDMATERIAL INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , VALOR DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDMATERIAL)
);

CREATE TABLE UTILIZA (
	IDMATERIAL INT NOT NULL
    , IDPROJETO INT NOT NULL
    , QTDE INT NOT NULL
    , VALOR DECIMAL(8,2) NOT NULL
    , PRIMARY KEY (IDMATERIAL, IDPROJETO)
    , FOREIGN KEY (IDMATERIAL) REFERENCES MATERIAL(IDMATERIAL)
    , FOREIGN KEY (IDPROJETO) REFERENCES PROJETO(IDPROJETO)
);
